version: '3'

services:
  db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - "dbdata:/var/lib/postgresql/data/pgdata"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  dbdata: