# Generated by Django 2.1 on 2018-08-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0005_auto_20180818_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
